name: Squash

on:
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Squash all the commits
        run: |
          git checkout --orphan init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Init"
          git branch -D master
          git branch -m master
          git push -f -u origin master
